version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  # backend:
  #   build: ./backend
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./backend/app.js:/app/app.js
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  local_pgdata:
  pgadmin-data:

