FROM node:21-alpine

WORKDIR /app

COPY package.json ./

RUN npm install

COPY . .

EXPOSE 3000

# https://stackoverflow.com/questions/39239686/nodemon-doesnt-restart-in-windows-docker-environment
CMD ["npx", "nodemon", "--legacy-watch", "app.js"]

